version: ~> 1.0

language: node_js
node_js:
  - "14"

# fix from https://benlimmer.com/2019/01/14/travis-ci-xvfb/
services:
  - xvfb
before_install:
  - node --version
  - npm --version
  - npx --version
script:
  - npm test


